# Site settings
title: Python Sul 2017
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Conferência Nacional Python organizada pela comunidade da região Sul. 3 dias de
  Tutoriais, palestras sobre a linguagem Python.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://pythonsul.org" # the base hostname & protocol for your site
twitter_username: pythonsul
github_username:  pythonsul

# Build settings
markdown: kramdown
